table:
  Type: 'AWS::DynamoDB::Table'
  DeletionPolicy: Retain
  Properties:
    TableName: ${self:provider.environment.DYNAMODB_TABLE}
    AttributeDefinitions:
      - AttributeName: dataType
        AttributeType: S
      - AttributeName: subscriptionType
        AttributeType: S
      - AttributeName: id
        AttributeType: S
      - AttributeName: institutionId
        AttributeType: S
    KeySchema:
      - AttributeName: dataType
        KeyType: HASH
      - AttributeName: id
        KeyType: RANGE
    ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    GlobalSecondaryIndexes:
      - IndexName: Subscription_Type
        KeySchema:
        - AttributeName: subscriptionType
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    LocalSecondaryIndexes:
      - IndexName: Institution_Subscription
        KeySchema:
        - AttributeName: dataType
          KeyType: HASH
        - AttributeName: institutionId
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
